# Numpy

### Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [1]:
import numpy as np
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
mean_a = np.array(a.mean(axis=0))
print(mean_a)

[2.  8.4]


### Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [3]:
a_centered = (a - mean_a)
print(a_centered)

a_centered.shape

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


(5, 2)

### Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [4]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp

8.0

In [5]:
a_centered.shape[0] #число наблюдений

5

In [6]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0

### Задание 4**

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [7]:
z = np.cov(a.T)
print(z)

[[1.  2. ]
 [2.  4.3]]


In [8]:
print(z[0, 1]) # искомое значение ковариации

2.0


### Задание 5**

Создайте одномерный массив z случайных нормально распределенных целых чисел от -50 до 50 включительно размерности 8. Найдите индексы положительных объектов.

In [1]:
import numpy as np
import random
z = np.random.randint(-50, 51, 8)

In [2]:
print(z)

[-14 -43 -44  21  46  37 -30  33]


In [3]:
print(np.where(z > 0)[0])

[3 4 5 7]


### Задание 6**

Создайте двумерный массив X случайных равномерно распределенных целых чисел от 0 до 255 включительно размерности 10 на 5. (Здесь снова считаем, что каждый столбец - это признак, а строка - наблюдение.)
Найдите среднее значение и стандартное отклонение по каждому признаку.
Вычислите массив X_standard, отняв от каждого признака среднее и поделив на стандартное отклонение.
Убедитесь, что теперь среднее в каждом признаке стало равное нулю, а стандартное отклонение равно единице.
Это называется стандартизация данных - важный процесс подготовки данных. Более подробно можно почитать здесь (https://wiki.loginom.ru/articles/data-standartization.html)

In [14]:
import numpy as np
import random

In [15]:
X = np.random.randint(256, size=(10, 5))
X

array([[114,  87,  41, 152,  47],
       [180,  92, 107,  80,  34],
       [ 48, 164, 127, 155,  71],
       [169, 192, 182,  20, 121],
       [115, 254,  39, 221, 166],
       [140, 159, 179, 174, 189],
       [  7, 230, 165,  90, 111],
       [158, 207,  86,  19,  89],
       [ 20, 226, 228,  94,  76],
       [ 94, 205,  58, 115,  95]])

In [16]:
mean = X.mean(axis=0)
mean

array([104.5, 181.6, 121.2, 112. ,  99.9])

In [17]:
std = X.std(axis=0)
std

array([58.42302628, 53.52980478, 62.46567057, 61.74787446, 46.44017657])

In [18]:
X_standard = (X - mean) / std
X_standard

array([[ 0.16260712, -1.76723977, -1.28390521,  0.64779558, -1.13909989],
       [ 1.29229868, -1.67383386, -0.22732486, -0.51823646, -1.41902992],
       [-0.96708445, -0.32878879,  0.092851  ,  0.69638025, -0.62230599],
       [ 1.10401676,  0.19428429,  0.97333462, -1.48992983,  0.45434797],
       [ 0.17972366,  1.35251754, -1.3159228 ,  1.76524295,  1.42333653],
       [ 0.60763713, -0.4221947 ,  0.92530824,  1.00408315,  1.91859736],
       [-1.66886254,  0.90416919,  0.70118514, -0.35628757,  0.23901718],
       [ 0.91573483,  0.47450201, -0.56350952, -1.50612472, -0.23471056],
       [-1.44634753,  0.82944446,  1.70973911, -0.29150801, -0.51464059],
       [-0.17972366,  0.43713965, -1.01175573,  0.04858467, -0.10551209]])

In [19]:
mean_X = X_standard.mean(axis=0)
mean_X

array([-8.32667268e-18,  9.99200722e-17, -4.44089210e-17, -2.56739074e-17,
       -1.20736754e-16])

In [20]:
std_X = X_standard.std(axis=0)
std_X

array([1., 1., 1., 1., 1.])

### Задание 7**

Создайте два одномерных массива размерности 512 с любыми значениями. Будем считать, что каждый массив - это наблюдение с 512 признаками. 
Найдите разницу между двумя массивами. Далее возведите разницу в квадрат, просуммируйте все элементы нового массива и возьмите корень квадратный.
Это получилась L2-норма (Евклидова метрика) — функция расстояния, благодаря которой можно считать насколько далеки точки друг от друга, насколько они похожи друг на друга. Более подробно здесь (https://wiki.loginom.ru/articles/euclid-distance.html)
Посчитайте L2 норму для этих двух массивов с помощью numpy.linalg.

In [11]:
import numpy as np
import random
from math import sqrt
from numpy.linalg import norm

a = np.random.randint(100, size=512)
b = np.random.randint(100, size=512)
c = a - b
square = np.power(c, 2)
square_root = sqrt(np.sum(square))
square_root

943.0249201373207

In [12]:
dist = norm(c, ord = 2)
dist

943.0249201373207

### Задание 8**

Используйте ранее созданный массив X.
Найдите минимальное значение и максимальное по каждому признаку.
Вычислите массив X_norm, отняв от каждого признака минимальное и поделив на разницу максимального и минимального.
Убедитесь, что теперь минимальное значение стало равно 0, а максимальное - 1.
Это называется нормализация данных - еще один из важных процессов подготовки данных. Более подробно здесь (https://wiki.loginom.ru/articles/data-normalization.html)


In [21]:
X_min = X.min(axis = 0)
X_min

array([ 7, 87, 39, 19, 34])

In [22]:
X_max = X.max(axis = 0)
X_max

array([180, 254, 228, 221, 189])

In [23]:
X_norm = (X - X_min)/(X_max - X_min)
X_norm

array([[0.61849711, 0.        , 0.01058201, 0.65841584, 0.08387097],
       [1.        , 0.02994012, 0.35978836, 0.3019802 , 0.        ],
       [0.23699422, 0.46107784, 0.46560847, 0.67326733, 0.23870968],
       [0.93641618, 0.62874251, 0.75661376, 0.0049505 , 0.56129032],
       [0.62427746, 1.        , 0.        , 1.        , 0.8516129 ],
       [0.76878613, 0.43113772, 0.74074074, 0.76732673, 1.        ],
       [0.        , 0.85628743, 0.66666667, 0.35148515, 0.49677419],
       [0.87283237, 0.71856287, 0.24867725, 0.        , 0.35483871],
       [0.07514451, 0.83233533, 1.        , 0.37128713, 0.27096774],
       [0.50289017, 0.70658683, 0.1005291 , 0.47524752, 0.39354839]])

In [24]:
X_norm_min = X_norm.min(axis = 0)
X_norm_min

array([0., 0., 0., 0., 0.])

In [25]:
X_norm_max = X_norm.max(axis = 0)
X_norm_max

array([1., 1., 1., 1., 1.])

# Pandas


### Задание 1

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский']. Затем создайте датафрейм books cо столбцами author_id, book_title и price, в которых соответственно содержатся данные: [1, 1, 1, 2, 2, 3, 3], ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], [450, 300, 350, 500, 450, 370, 290].

In [26]:
import pandas as pd
import numpy as np

In [27]:
authors = pd.DataFrame({
    "author_id": [1, 2, 3], 
    "author_name": ['Тургенев', 'Чехов', 'Островский']})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [28]:
books = pd.DataFrame({
    "author_id": [1, 1, 1, 2, 2, 3, 3], 
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price": [450, 300, 350, 500, 450, 370, 290]})
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [29]:
authors_price = pd.merge(authors, books, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [30]:
top5 = authors_price.nlargest(5, "price")
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца: author_name, min_price, max_price и mean_price, в которых должны содержаться соответственно имя автора,минимальная, максимальная и средняя цена на книги этого автора.

In [31]:
authors_stat = authors_price.groupby('author_name').agg({'price':['min', 'max', 'mean']})
authors_stat = authors_stat.rename(columns={'min':'min_price', 'max':'max_price', 'mean':'mean_price'})
authors_stat

price                      
            min_price max_price  mean_price
author_name                                
Островский        290       370  330.000000
Тургенев          300       450  366.666667
Чехов             450       500  475.000000

### Задание 5*

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:

['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.

Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [32]:
authors_price['cover'] = 'твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'

In [33]:
book_info = authors_price.pivot_table('price', index='author_name', columns='cover', aggfunc=np.sum)
book_info['мягкая'] = book_info['мягкая'].fillna(0)
book_info['твердая'] = book_info['твердая'].fillna(0)
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [34]:
book_info.to_pickle('book_info.pkl')

In [35]:
book_info2 = pd.read_pickle('book_info.pkl')

In [36]:
book_info.equals(book_info2)

True

### Задание 6**
В этом задании будем работать с датасетом, в котором представлены данные по сериалам и фильмам на Netflix (Netflix Movies and TV Shows).
Ознакомьтесь с описанием данных и скачайте датасет netflix_titles.csv с сайта Kaggle.com https://www.kaggle.com/shivamb/netflix-shows

Считайте датасет. Посмотрите, сколько наблюдений и сколько признаков есть в этом наборе данных.

In [3]:
import numpy as np
import pandas as pd

netflix = pd.read_csv('netflix_titles.csv')
df = pd.DataFrame(netflix)
df

show_id     type                                    title  \
0         s1  TV Show                                       3%   
1         s2    Movie                                     7:19   
2         s3    Movie                                    23:59   
3         s4    Movie                                        9   
4         s5    Movie                                       21   
...      ...      ...                                      ...   
7782   s7783    Movie                                     Zozo   
7783   s7784    Movie                                   Zubaan   
7784   s7785    Movie                        Zulu Man in Japan   
7785   s7786  TV Show                    Zumbo's Just Desserts   
7786   s7787    Movie  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS   

               director                                               cast  \
0                   NaN  João Miguel, Bianca Comparato, Michel Gomes, R...   
1     Jorge Michel Grau  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...   
2          Gilbert Chan  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...   
3           Shane Acker  Elijah Wood, John C. Reilly, Jennifer Connelly...   
4        Robert Luketic  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...   
...                 ...                                                ...   
7782        Josef Fares  Imad Creidi, Antoinette Turk, Elias Gergi, Car...   
7783        Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...   
7784                NaN                                            Nasty C   
7785                NaN                         Adriano Zumbo, Rachel Khoo   
7786           Sam Dunn                                                NaN   

                                                country          date_added  \
0                                                Brazil     August 14, 2020   
1                                                Mexico   December 23, 2016   
2                                             Singapore   December 20, 2018   
3                                         United States   November 16, 2017   
4                                         United States     January 1, 2020   
...                                                 ...                 ...   
7782  Sweden, Czech Republic, United Kingdom, Denmar...    October 19, 2020   
7783                                              India       March 2, 2019   
7784                                                NaN  September 25, 2020   
7785                                          Australia    October 31, 2020   
7786              United Kingdom, Canada, United States       March 1, 2020   

      release_year rating   duration  \
0             2020  TV-MA  4 Seasons   
1             2016  TV-MA     93 min   
2             2011      R     78 min   
3             2009  PG-13     80 min   
4             2008  PG-13    123 min   
...            ...    ...        ...   
7782          2005  TV-MA     99 min   
7783          2015  TV-14    111 min   
7784          2019  TV-MA     44 min   
7785          2019  TV-PG   1 Season   
7786          2019  TV-MA     90 min   

                                              listed_in  \
0     International TV Shows, TV Dramas, TV Sci-Fi &...   
1                          Dramas, International Movies   
2                   Horror Movies, International Movies   
3     Action & Adventure, Independent Movies, Sci-Fi...   
4                                                Dramas   
...                                                 ...   
7782                       Dramas, International Movies   
7783     Dramas, International Movies, Music & Musicals   
7784  Documentaries, International Movies, Music & M...   
7785                 International TV Shows, Reality TV   
7786                    Documentaries, Music & Musicals   

                                            description  
0     In a future where the elite inhabit an island ...  
1     After a devast

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64 
 8   rating        7780 non-null   object
 9   duration      7787 non-null   object
 10  listed_in     7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(1), object(11)
memory usage: 730.2+ KB


Посчитайте, как много сериалов и фильмов представлено в этом датасете.

In [5]:
df.value_counts('type') # другой вариант кода - df.type.value_counts()

type
Movie      5377
TV Show    2410
dtype: int64

Посчитайте, как много пропущенных значений (NaN) есть в признаках director и country.

In [6]:
df['director'].isnull().sum()

2389

In [7]:
df['country'].isnull().sum()

507

Посчитайте, сколько фильмов выпустили раньше 2003 года.

In [8]:
release_year = df['release_year']
release_year.loc[release_year > 2003].count()

7174

Посчитайте, какая страна чаще всего выпускает фильмы на Netflix.

In [9]:
df.value_counts('country').idxmax()

'United States'

In [10]:
df.value_counts('country').max()

2555

### Задание 7**
В этом датасете есть признак date_added (дата добавления сериала/фильма на платформу), на основе этого признака создайте три новых: year_added - год добавления, month_added - месяц добавления и day_added - день добавления.


In [11]:
date_added = df['date_added']
date_added

0          August 14, 2020
1        December 23, 2016
2        December 20, 2018
3        November 16, 2017
4          January 1, 2020
               ...        
7782      October 19, 2020
7783         March 2, 2019
7784    September 25, 2020
7785      October 31, 2020
7786         March 1, 2020
Name: date_added, Length: 7787, dtype: object

In [12]:
df['date_added'].head(2)

0      August 14, 2020
1    December 23, 2016
Name: date_added, dtype: object

In [13]:
import datetime as dt

In [14]:
df['date_added'] = pd.to_datetime(df['date_added'], infer_datetime_format=True)
df['date_added'].head(5)

0   2020-08-14
1   2016-12-23
2   2018-12-20
3   2017-11-16
4   2020-01-01
Name: date_added, dtype: datetime64[ns]

In [15]:
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month
df['day_added'] = df['date_added'].dt.day

In [16]:
# df.fillna({'year_added': 0}, inplace=True)
# df.fillna({'month_added': 0}, inplace=True)
# df.fillna({'day_added': 0}, inplace=True)
# df = df.astype({'year_added':'int','month_added':'int', 'day_added':'int'})

In [17]:
df['year_added'].head(5)

0    2020.0
1    2016.0
2    2018.0
3    2017.0
4    2020.0
Name: year_added, dtype: float64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   show_id       7787 non-null   object        
 1   type          7787 non-null   object        
 2   title         7787 non-null   object        
 3   director      5398 non-null   object        
 4   cast          7069 non-null   object        
 5   country       7280 non-null   object        
 6   date_added    7777 non-null   datetime64[ns]
 7   release_year  7787 non-null   int64         
 8   rating        7780 non-null   object        
 9   duration      7787 non-null   object        
 10  listed_in     7787 non-null   object        
 11  description   7787 non-null   object        
 12  year_added    7777 non-null   float64       
 13  month_added   7777 non-null   float64       
 14  day_added     7777 non-null   float64       
dtypes: datetime64[ns](1), float64(3), int6

### Задание 8**
Выберите только наблюдения, где страна 'United States', 'India' или 'United Kingdom'
Для каждой страны посчитайте общее количество фильмов и сериалов по месяцам выпуска. Столбцы нового сводного датафрейма должны называться, как месяца в признаке month_added, а индексов будет два: страна и тип.


In [20]:
pd.pivot_table(df[df.country.isin(['United States', 'India', 'United Kingdom'])],
               values='title',
               index=['country', 'type'],
               columns='month_added',
               aggfunc='count')

month_added             1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0   \
country        type                                                            
India          Movie      65    45    83    72    65    40    69    70    55   
               TV Show     2     2    12    14     5     7     7     4     1   
United Kingdom Movie      17    16    20    12    18    14     7    18    16   
               TV Show    13    17    34    14    10     7    16    22    19   
United States  Movie     245   118   156   139   109   112   144   143   128   
               TV Show    61    45    49    47    46    43    55    55    81   

month_added             10.0  11.0  12.0  
country        type                       
India          Movie      97    87   104  
               TV Show     8     3     6  
United Kingdom Movie      22     8    25  
               TV Show    22     9    20  
United States  Movie     172   210   174  
               TV Show    68    69    80

In [19]:
data_grp = df.groupby('country') 

In [20]:
df_us = data_grp.get_group('United States')
df_uk = data_grp.get_group('United Kingdom')
df_ind = data_grp.get_group('India')

In [21]:
df_ind

show_id   type                     title            director  \
8         s9  Movie                       706       Shravan Kumar   
9        s10  Movie                      1920        Vikram Bhatt   
18       s19  Movie                    15-Aug  Swapnaneel Jayakar   
20       s21  Movie      ​​Kuch Bheege Alfaaz                Onir   
21       s22  Movie              ​Goli Soda 2        Vijay Milton   
...      ...    ...                       ...                 ...   
7764   s7765  Movie                      Zero          Aanand Rai   
7769   s7770  Movie  Zindagi Na Milegi Dobara         Zoya Akhtar   
7776   s7777  Movie                  Zokkomon    Satyajit Bhatkal   
7780   s7781  Movie                       Zoo        Shlok Sharma   
7783   s7784  Movie                    Zubaan         Mozez Singh   

                                                   cast country date_added  \
8     Divya Dutta, Atul Kulkarni, Mohan Agashe, Anup...   India 2019-04-01   
9     Rajneesh Duggal, Adah Sharma, Indraneil Sengup...   India 2017-12-15   
18    Rahul Pethe, Mrunmayee Deshpande, Adinath Koth...   India 2019-03-29   
20    Geetanjali Thapa, Zain Khan Durrani, Shray Rai...   India 2018-09-01   
21    Samuthirakani, Bharath Seeni, Vinoth, Esakki B...   India 2018-09-15   
...                                                 ...     ...        ...   
7764  Shah Rukh Khan, Anushka Sharma, Katrina Kaif, ...   India 2019-05-21   
7769  Hrithik Roshan, Abhay Deol, Farhan Akhtar, Kat...   India 2019-12-15   
7776  Darsheel Safary, Anupam Kher, Manjari Fadnis, ...   India 2018-11-01   
7780  Shashank Arora, Shweta Tripathi, Rahul Kumar, ...   India 2018-07-01   
7783  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...   India 2019-03-02   

      release_year rating duration  \
8             2019  TV-14  118 min   
9             2008  TV-MA  143 min   
18            2019  TV-14  124 min   
20            2018  TV-14  110 min   
21            2018  TV-14  128 min   
...            ...    ...      ...   
7764          2018  TV-14  159 min   
7769          2011  TV-14  154 min   
7776          2011     PG  104 min   
7780          2018  TV-MA   94 min   
7783          2015  TV-14  111 min   

                                             listed_in  \
8                  Horror Movies, International Movies   
9       Horror Movies, International Movies, Thrillers   
18                Comedies, Dramas, Independent Movies   
20    Dramas, Independent Movies, International Movies   
21    Action & Adventure, Dramas, International Movies   
...                                                ...   
7764            Comedies, Dramas, International Movies   
7769            Comedies, Dramas, International Movies   
7776                  Children & Family Movies, Dramas   
7780  Dramas, Independent Movies, International Movies   
7783    Dramas, International Movies, Music & Musicals   

                                            description  year_added  \
8     When a doctor goes missing, his psychiatrist w...      2019.0   
9     An architect and his wife move into a castle t...      2017.0   
18    On India's Independence Day, a zany mishap in ...      2019.0   
20    After accidentally connecting over the Interne...      2018.0   
21    A taxi driver, a gangster and an athlete strug...      2018.0   
...                                                 ...         ...   
7764  Through his relationships with two wildly diff...      2019.0   
7769  Three friends on an adventurous road trip/bach...      2019.0   
7776  When his cruel uncle abandons him, a young orp...      2018.0   
7780  A drug dealer starts having doubts about his t...      2018.0   
7783  A scrappy but poor boy worms his way into a ty...      2019.0   

      month_added  day_added  
8             4.0        1.0  
9            12.0       15.0  
18            3.0       29.0  
20            9.0        1.0  
21            9.0       15.0  
...           ...        ...  
7764          5

In [22]:
conc_df = pd.concat([df_us, df_uk, df_ind], sort=False, axis=0)

In [23]:
conc_df

show_id   type                     title          director  \
3         s4  Movie                         9       Shane Acker   
4         s5  Movie                        21    Robert Luketic   
7         s8  Movie                       187    Kevin Reynolds   
10       s11  Movie                      1922      Zak Hilditch   
14       s15  Movie                      3022        John Suits   
...      ...    ...                       ...               ...   
7764   s7765  Movie                      Zero        Aanand Rai   
7769   s7770  Movie  Zindagi Na Milegi Dobara       Zoya Akhtar   
7776   s7777  Movie                  Zokkomon  Satyajit Bhatkal   
7780   s7781  Movie                       Zoo      Shlok Sharma   
7783   s7784  Movie                    Zubaan       Mozez Singh   

                                                   cast        country  \
3     Elijah Wood, John C. Reilly, Jennifer Connelly...  United States   
4     Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...  United States   
7     Samuel L. Jackson, John Heard, Kelly Rowan, Cl...  United States   
10    Thomas Jane, Molly Parker, Dylan Schmid, Kaitl...  United States   
14    Omar Epps, Kate Walsh, Miranda Cosgrove, Angus...  United States   
...                                                 ...            ...   
7764  Shah Rukh Khan, Anushka Sharma, Katrina Kaif, ...          India   
7769  Hrithik Roshan, Abhay Deol, Farhan Akhtar, Kat...          India   
7776  Darsheel Safary, Anupam Kher, Manjari Fadnis, ...          India   
7780  Shashank Arora, Shweta Tripathi, Rahul Kumar, ...          India   
7783  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India   

     date_added  release_year rating duration  \
3    2017-11-16          2009  PG-13   80 min   
4    2020-01-01          2008  PG-13  123 min   
7    2019-11-01          1997      R  119 min   
10   2017-10-20          2017  TV-MA  103 min   
14   2020-03-19          2019      R   91 min   
...         ...           ...    ...      ...   
7764 2019-05-21          2018  TV-14  159 min   
7769 2019-12-15          2011  TV-14  154 min   
7776 2018-11-01          2011     PG  104 min   
7780 2018-07-01          2018  TV-MA   94 min   
7783 2019-03-02          2015  TV-14  111 min   

                                              listed_in  \
3     Action & Adventure, Independent Movies, Sci-Fi...   
4                                                Dramas   
7                                                Dramas   
10                                    Dramas, Thrillers   
14      Independent Movies, Sci-Fi & Fantasy, Thrillers   
...                                                 ...   
7764             Comedies, Dramas, International Movies   
7769             Comedies, Dramas, International Movies   
7776                   Children & Family Movies, Dramas   
7780   Dramas, Independent Movies, International Movies   
7783     Dramas, International Movies, Music & Musicals   

                                            description  year_added  \
3     In a postapocalyptic world, rag-doll robots hi...      2017.0   
4     A brilliant group of students become card-coun...      2020.0   
7     After one of his high school students attacks ...      2019.0   
10    A farmer pens a confession admitting to his wi...      2017.0   
14    Stranded when the Earth is suddenly destroyed ...      2020.0   
...                                                 ...         ...   
7764  Through his relationships with two wildly diff...      2019.0   
7769  Three friends on an adventurous road trip/bach...      2019.0   
7776  When his cruel uncle abandons him, a young orp...      2018.0   
7780  A drug dealer starts having doubts about his t...      2018.0   
7783  A scrappy but poor boy worms his way into a ty...      2019.0   

      month_added  day_added  
3            11.0       16.0  
4             1.0        1.0  
7            11.0        1.0  
10           10.0       20.0  
14   

In [24]:
pd.crosstab(index=[conc_df['country'], 
                   conc_df['type']], 
            columns=conc_df['month_added'], 
            values=conc_df['type'], 
            aggfunc='count')

month_added             1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0   \
country        type                                                            
India          Movie      65    45    83    72    65    40    69    70    55   
               TV Show     2     2    12    14     5     7     7     4     1   
United Kingdom Movie      17    16    20    12    18    14     7    18    16   
               TV Show    13    17    34    14    10     7    16    22    19   
United States  Movie     245   118   156   139   109   112   144   143   128   
               TV Show    61    45    49    47    46    43    55    55    81   

month_added             10.0  11.0  12.0  
country        type                       
India          Movie      97    87   104  
               TV Show     8     3     6  
United Kingdom Movie      22     8    25  
               TV Show    22     9    20  
United States  Movie     172   210   174  
               TV Show    68    69    80